var annotated =
[
    [ "std", null, [
      [ "hash< zk::acl_rule >", "classstd_1_1hash_3_01zk_1_1acl__rule_01_4.html", "classstd_1_1hash_3_01zk_1_1acl__rule_01_4" ],
      [ "hash< zk::version >", "structstd_1_1hash_3_01zk_1_1version_01_4.html", "structstd_1_1hash_3_01zk_1_1version_01_4" ],
      [ "hash< zk::transaction_id >", "structstd_1_1hash_3_01zk_1_1transaction__id_01_4.html", "structstd_1_1hash_3_01zk_1_1transaction__id_01_4" ]
    ] ],
    [ "zk", null, [
      [ "server", null, [
        [ "detail", null, [
          [ "pipe_closed", "classzk_1_1server_1_1detail_1_1pipe__closed.html", "classzk_1_1server_1_1detail_1_1pipe__closed" ],
          [ "pipe", "classzk_1_1server_1_1detail_1_1pipe.html", "classzk_1_1server_1_1detail_1_1pipe" ],
          [ "subprocess", "classzk_1_1server_1_1detail_1_1subprocess.html", "classzk_1_1server_1_1detail_1_1subprocess" ]
        ] ],
        [ "package_registry", "classzk_1_1server_1_1package__registry.html", "classzk_1_1server_1_1package__registry" ],
        [ "server", "classzk_1_1server_1_1server.html", "classzk_1_1server_1_1server" ]
      ] ],
      [ "acl_rule", "classzk_1_1acl__rule.html", "classzk_1_1acl__rule" ],
      [ "acl", "classzk_1_1acl.html", "classzk_1_1acl" ],
      [ "acls", "classzk_1_1acls.html", null ],
      [ "client", "classzk_1_1client.html", "classzk_1_1client" ],
      [ "connection", "classzk_1_1connection.html", "classzk_1_1connection" ],
      [ "connection_zk_commit_completer", "structzk_1_1connection__zk__commit__completer.html", "structzk_1_1connection__zk__commit__completer" ],
      [ "connection_zk", "classzk_1_1connection__zk.html", "classzk_1_1connection__zk" ],
      [ "error", "classzk_1_1error.html", "classzk_1_1error" ],
      [ "system_error", "classzk_1_1system__error.html", "classzk_1_1system__error" ],
      [ "runtime_inconsistency", "classzk_1_1runtime__inconsistency.html", "classzk_1_1runtime__inconsistency" ],
      [ "data_inconsistency", "classzk_1_1data__inconsistency.html", "classzk_1_1data__inconsistency" ],
      [ "connection_loss", "classzk_1_1connection__loss.html", "classzk_1_1connection__loss" ],
      [ "marshalling_error", "classzk_1_1marshalling__error.html", "classzk_1_1marshalling__error" ],
      [ "unimplemented", "classzk_1_1unimplemented.html", "classzk_1_1unimplemented" ],
      [ "operation_timeout", "classzk_1_1operation__timeout.html", "classzk_1_1operation__timeout" ],
      [ "invalid_arguments", "classzk_1_1invalid__arguments.html", "classzk_1_1invalid__arguments" ],
      [ "invalid_handle_state", "classzk_1_1invalid__handle__state.html", "classzk_1_1invalid__handle__state" ],
      [ "unknown_session", "classzk_1_1unknown__session.html", "classzk_1_1unknown__session" ],
      [ "new_configuration_no_quorum", "classzk_1_1new__configuration__no__quorum.html", "classzk_1_1new__configuration__no__quorum" ],
      [ "reconfiguration_in_progress", "classzk_1_1reconfiguration__in__progress.html", "classzk_1_1reconfiguration__in__progress" ],
      [ "api_error", "classzk_1_1api__error.html", "classzk_1_1api__error" ],
      [ "no_node", "classzk_1_1no__node.html", "classzk_1_1no__node" ],
      [ "not_authenticated", "classzk_1_1not__authenticated.html", "classzk_1_1not__authenticated" ],
      [ "bad_version", "classzk_1_1bad__version.html", "classzk_1_1bad__version" ],
      [ "no_children_for_ephemerals", "classzk_1_1no__children__for__ephemerals.html", "classzk_1_1no__children__for__ephemerals" ],
      [ "node_exists", "classzk_1_1node__exists.html", "classzk_1_1node__exists" ],
      [ "not_empty", "classzk_1_1not__empty.html", "classzk_1_1not__empty" ],
      [ "session_expired", "classzk_1_1session__expired.html", "classzk_1_1session__expired" ],
      [ "invalid_callback", "classzk_1_1invalid__callback.html", "classzk_1_1invalid__callback" ],
      [ "invalid_acl", "classzk_1_1invalid__acl.html", "classzk_1_1invalid__acl" ],
      [ "authentication_failed", "classzk_1_1authentication__failed.html", "classzk_1_1authentication__failed" ],
      [ "closing", "classzk_1_1closing.html", "classzk_1_1closing" ],
      [ "no_response", "classzk_1_1no__response.html", "classzk_1_1no__response" ],
      [ "session_moved", "classzk_1_1session__moved.html", "classzk_1_1session__moved" ],
      [ "server_read_only", "classzk_1_1server__read__only.html", "classzk_1_1server__read__only" ],
      [ "ephemeral_on_local_session", "classzk_1_1ephemeral__on__local__session.html", "classzk_1_1ephemeral__on__local__session" ],
      [ "no_watcher", "classzk_1_1no__watcher.html", "classzk_1_1no__watcher" ],
      [ "reconfiguration_disabled", "classzk_1_1reconfiguration__disabled.html", "classzk_1_1reconfiguration__disabled" ],
      [ "transaction_failed", "classzk_1_1transaction__failed.html", "classzk_1_1transaction__failed" ],
      [ "unknown_error", "classzk_1_1unknown__error.html", "classzk_1_1unknown__error" ],
      [ "op", "classzk_1_1op.html", "classzk_1_1op" ],
      [ "multi_op", "classzk_1_1multi__op.html", "classzk_1_1multi__op" ],
      [ "multi_result", "classzk_1_1multi__result.html", "classzk_1_1multi__result" ],
      [ "get_result", "classzk_1_1get__result.html", "classzk_1_1get__result" ],
      [ "get_children_result", "classzk_1_1get__children__result.html", "classzk_1_1get__children__result" ],
      [ "exists_result", "classzk_1_1exists__result.html", "classzk_1_1exists__result" ],
      [ "create_result", "classzk_1_1create__result.html", "classzk_1_1create__result" ],
      [ "set_result", "classzk_1_1set__result.html", "classzk_1_1set__result" ],
      [ "get_acl_result", "classzk_1_1get__acl__result.html", "classzk_1_1get__acl__result" ],
      [ "event", "classzk_1_1event.html", "classzk_1_1event" ],
      [ "watch_result", "classzk_1_1watch__result.html", "classzk_1_1watch__result" ],
      [ "watch_children_result", "classzk_1_1watch__children__result.html", "classzk_1_1watch__children__result" ],
      [ "watch_exists_result", "classzk_1_1watch__exists__result.html", "classzk_1_1watch__exists__result" ],
      [ "strong_id", "structzk_1_1strong__id.html", "structzk_1_1strong__id" ],
      [ "basic_version", "structzk_1_1basic__version.html", null ],
      [ "version", "structzk_1_1version.html", null ],
      [ "acl_version", "structzk_1_1acl__version.html", null ],
      [ "child_version", "structzk_1_1child__version.html", null ],
      [ "transaction_id", "structzk_1_1transaction__id.html", null ],
      [ "stat", "structzk_1_1stat.html", "structzk_1_1stat" ]
    ] ]
];