var annotated =
[
    [ "std", null, [
      [ "hash< zk::acl_rule >", "classstd_1_1hash_3_01zk_1_1acl__rule_01_4.html", "classstd_1_1hash_3_01zk_1_1acl__rule_01_4" ],
      [ "hash< zk::acl_version >", "structstd_1_1hash_3_01zk_1_1acl__version_01_4.html", "structstd_1_1hash_3_01zk_1_1acl__version_01_4" ],
      [ "hash< zk::child_version >", "structstd_1_1hash_3_01zk_1_1child__version_01_4.html", "structstd_1_1hash_3_01zk_1_1child__version_01_4" ],
      [ "hash< zk::server::server_id >", "structstd_1_1hash_3_01zk_1_1server_1_1server__id_01_4.html", "structstd_1_1hash_3_01zk_1_1server_1_1server__id_01_4" ],
      [ "hash< zk::transaction_id >", "structstd_1_1hash_3_01zk_1_1transaction__id_01_4.html", "structstd_1_1hash_3_01zk_1_1transaction__id_01_4" ],
      [ "hash< zk::version >", "structstd_1_1hash_3_01zk_1_1version_01_4.html", "structstd_1_1hash_3_01zk_1_1version_01_4" ],
      [ "is_error_code_enum< zk::error_code >", "structstd_1_1is__error__code__enum_3_01zk_1_1error__code_01_4.html", null ]
    ] ],
    [ "zk", null, [
      [ "server", null, [
        [ "classpath", "classzk_1_1server_1_1classpath.html", "classzk_1_1server_1_1classpath" ],
        [ "configuration", "classzk_1_1server_1_1configuration.html", "classzk_1_1server_1_1configuration" ],
        [ "package_registry", "classzk_1_1server_1_1package__registry.html", "classzk_1_1server_1_1package__registry" ],
        [ "server", "classzk_1_1server_1_1server.html", "classzk_1_1server_1_1server" ],
        [ "server_group", "classzk_1_1server_1_1server__group.html", "classzk_1_1server_1_1server__group" ],
        [ "server_id", "structzk_1_1server_1_1server__id.html", "structzk_1_1server_1_1server__id" ]
      ] ],
      [ "acl", "classzk_1_1acl.html", "classzk_1_1acl" ],
      [ "acl_rule", "classzk_1_1acl__rule.html", "classzk_1_1acl__rule" ],
      [ "acl_version", "structzk_1_1acl__version.html", null ],
      [ "acls", "classzk_1_1acls.html", null ],
      [ "authentication_failed", "classzk_1_1authentication__failed.html", "classzk_1_1authentication__failed" ],
      [ "basic_version", "structzk_1_1basic__version.html", null ],
      [ "check_failed", "classzk_1_1check__failed.html", "classzk_1_1check__failed" ],
      [ "child_version", "structzk_1_1child__version.html", null ],
      [ "client", "classzk_1_1client.html", "classzk_1_1client" ],
      [ "closed", "classzk_1_1closed.html", "classzk_1_1closed" ],
      [ "connection", "classzk_1_1connection.html", "classzk_1_1connection" ],
      [ "connection_loss", "classzk_1_1connection__loss.html", "classzk_1_1connection__loss" ],
      [ "connection_params", "classzk_1_1connection__params.html", "classzk_1_1connection__params" ],
      [ "connection_zk", "classzk_1_1connection__zk.html", "classzk_1_1connection__zk" ],
      [ "connection_zk_commit_completer", "structzk_1_1connection__zk__commit__completer.html", "structzk_1_1connection__zk__commit__completer" ],
      [ "create_result", "classzk_1_1create__result.html", "classzk_1_1create__result" ],
      [ "entry_exists", "classzk_1_1entry__exists.html", "classzk_1_1entry__exists" ],
      [ "ephemeral_on_local_session", "classzk_1_1ephemeral__on__local__session.html", "classzk_1_1ephemeral__on__local__session" ],
      [ "error", "classzk_1_1error.html", "classzk_1_1error" ],
      [ "error_category_impl", "classzk_1_1error__category__impl.html", "classzk_1_1error__category__impl" ],
      [ "event", "classzk_1_1event.html", "classzk_1_1event" ],
      [ "exists_result", "classzk_1_1exists__result.html", "classzk_1_1exists__result" ],
      [ "get_acl_result", "classzk_1_1get__acl__result.html", "classzk_1_1get__acl__result" ],
      [ "get_children_result", "classzk_1_1get__children__result.html", "classzk_1_1get__children__result" ],
      [ "get_result", "classzk_1_1get__result.html", "classzk_1_1get__result" ],
      [ "invalid_arguments", "classzk_1_1invalid__arguments.html", "classzk_1_1invalid__arguments" ],
      [ "invalid_connection_state", "classzk_1_1invalid__connection__state.html", "classzk_1_1invalid__connection__state" ],
      [ "invalid_ensemble_state", "classzk_1_1invalid__ensemble__state.html", "classzk_1_1invalid__ensemble__state" ],
      [ "marshalling_error", "classzk_1_1marshalling__error.html", "classzk_1_1marshalling__error" ],
      [ "multi_op", "classzk_1_1multi__op.html", "classzk_1_1multi__op" ],
      [ "multi_result", "classzk_1_1multi__result.html", "classzk_1_1multi__result" ],
      [ "new_configuration_no_quorum", "classzk_1_1new__configuration__no__quorum.html", "classzk_1_1new__configuration__no__quorum" ],
      [ "no_children_for_ephemerals", "classzk_1_1no__children__for__ephemerals.html", "classzk_1_1no__children__for__ephemerals" ],
      [ "no_entry", "classzk_1_1no__entry.html", "classzk_1_1no__entry" ],
      [ "not_authorized", "classzk_1_1not__authorized.html", "classzk_1_1not__authorized" ],
      [ "not_empty", "classzk_1_1not__empty.html", "classzk_1_1not__empty" ],
      [ "not_implemented", "classzk_1_1not__implemented.html", "classzk_1_1not__implemented" ],
      [ "op", "classzk_1_1op.html", "classzk_1_1op" ],
      [ "read_only_connection", "classzk_1_1read__only__connection.html", "classzk_1_1read__only__connection" ],
      [ "reconfiguration_disabled", "classzk_1_1reconfiguration__disabled.html", "classzk_1_1reconfiguration__disabled" ],
      [ "reconfiguration_in_progress", "classzk_1_1reconfiguration__in__progress.html", "classzk_1_1reconfiguration__in__progress" ],
      [ "session_expired", "classzk_1_1session__expired.html", "classzk_1_1session__expired" ],
      [ "set_result", "classzk_1_1set__result.html", "classzk_1_1set__result" ],
      [ "stat", "structzk_1_1stat.html", "structzk_1_1stat" ],
      [ "strong_id", "structzk_1_1strong__id.html", "structzk_1_1strong__id" ],
      [ "transaction_failed", "classzk_1_1transaction__failed.html", "classzk_1_1transaction__failed" ],
      [ "transaction_id", "structzk_1_1transaction__id.html", null ],
      [ "transport_error", "classzk_1_1transport__error.html", "classzk_1_1transport__error" ],
      [ "version", "structzk_1_1version.html", null ],
      [ "version_mismatch", "classzk_1_1version__mismatch.html", "classzk_1_1version__mismatch" ],
      [ "watch_children_result", "classzk_1_1watch__children__result.html", "classzk_1_1watch__children__result" ],
      [ "watch_exists_result", "classzk_1_1watch__exists__result.html", "classzk_1_1watch__exists__result" ],
      [ "watch_result", "classzk_1_1watch__result.html", "classzk_1_1watch__result" ]
    ] ]
];