#!/bin/bash -e

# TODO: 99% sure there is a better way to do this
GCC_VERSION_MAJOR=$(c++ --version | head -1 | grep -Po '\d\.\d\.\d' | grep -Po '^\d+')

coveralls                                                       \
    --build-root $1                                             \
    --exclude-pattern '*_test.cpp'                              \
    --exclude-pattern bits                                      \
    --gcov-options '\-lp' --gcov "gcov-${GCC_VERSION_MAJOR}"
